//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bushman.RevitMultiLanguageAddInExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bushman.RevitMultiLanguageAddInExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cmd_01_32x32 {
            get {
                object obj = ResourceManager.GetObject("cmd_01_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cmd_02_32x32 {
            get {
                object obj = ResourceManager.GetObject("cmd_02_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is long description of first command..
        /// </summary>
        internal static string Command_01_long_description {
            get {
                return ResourceManager.GetString("Command_01_long_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first command.
        /// </summary>
        internal static string Command_01_text {
            get {
                return ResourceManager.GetString("Command_01_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is tooltip of the first command..
        /// </summary>
        internal static string Command_01_tooltip {
            get {
                return ResourceManager.GetString("Command_01_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is long description of second command..
        /// </summary>
        internal static string Command_02_long_description {
            get {
                return ResourceManager.GetString("Command_02_long_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second command.
        /// </summary>
        internal static string Command_02_text {
            get {
                return ResourceManager.GetString("Command_02_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is tooltip of the second command..
        /// </summary>
        internal static string Command_02_tooltip {
            get {
                return ResourceManager.GetString("Command_02_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flower_01 {
            get {
                object obj = ResourceManager.GetObject("flower_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flower_02 {
            get {
                object obj = ResourceManager.GetObject("flower_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevitMultiLanguageAddInExample.chm.
        /// </summary>
        internal static string HelpFileName {
            get {
                return ResourceManager.GetString("HelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My commands panel.
        /// </summary>
        internal static string Ribbon_panel_name {
            get {
                return ResourceManager.GetString("Ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLanguageAddInExample.
        /// </summary>
        internal static string Ribbon_tab_name {
            get {
                return ResourceManager.GetString("Ribbon_tab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, Revit!.
        /// </summary>
        internal static string TaskDialog_Message_01 {
            get {
                return ResourceManager.GetString("TaskDialog_Message_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Revit!.
        /// </summary>
        internal static string TaskDialog_Message_02 {
            get {
                return ResourceManager.GetString("TaskDialog_Message_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string TaskDialog_Title {
            get {
                return ResourceManager.GetString("TaskDialog_Title", resourceCulture);
            }
        }
    }
}
